repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.11
repos:
- hooks:
  - id: commitizen
    stages: [commit-msg]
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.42.1
